dist: bionic

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export MODEL_BASE_PATH=/tmp/codebook_automation/models/

script:
  - pytest