dist: bionic

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

services:
  - redis-server

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export CBA_API_DATA_ROOT=/tmp
  - export CBA_API_REDIS_HOST=localhost
  - export CBA_API_REDIS_PORT=6379

script:
  - pytest
