# Check .env file for correctness!
version: '3'

networks:
  cba_codeanno:

services:
  redis:
    image: 'redis:latest'
    ports:
      - "${CBA_REDIS_EXPOSED_PORT}:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - cba_codeanno

  cba_api:
    image: 'uhhlt/codebook_automation_api:latest'
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./config:/app/config
    environment:
      - "CBA_API_DATA_ROOT=${CBA_API_DATA_ROOT}"
      - "CBA_API_REDIS_HOST=${CBA_API_REDIS_HOST}"
      - "CBA_API_REDIS_PORT=${CBA_API_REDIS_PORT}"
    ports:
      - "${CBA_API_EXPOSED_PORT}:80"
    networks:
      - cba_codeanno

  cba_app:
    image: 'uhhlt/codebook_automation_app:latest'
    depends_on:
      - cba_api
    environment:
      - "CBA_APP_DEPLOY=${CBA_APP_DEPLOY}"
      - "CBA_APP_API_HOST=${CBA_APP_API_HOST}"
      - "CBA_APP_API_PORT=${CBA_APP_API_PORT}"
      # TODO this cannot be set at or just before runtime...
      # see https://stackoverflow.com/questions/65428478/nuxt-js-router-config-at-runtime-or-just-before-the-application-starts
      - "CBA_APP_CONTEXT_PATH=${CBA_APP_CONTEXT_PATH}"
    ports:
      - "${CBA_APP_EXPOSED_PORT}:3000"
    networks:
      - cba_codeanno
  db:
    image: "mysql:5"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codebookanno
      - MYSQL_USER=codebookanno
      - MYSQL_PASSWORD=codebookanno
      - MYSQL_PORT=3306
      - MYSQL_HOST=localhost
    volumes:
      - ${PWD}/mysql-data-2:/var/lib/mysql
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pcodebookanno", "-ucodebookanno"]
      interval: 20s
      timeout: 100s
      retries: 10
    networks:
      - cba_codeanno

  codeanno:
    image: "uhhlt/codebookanno:cba"
    ports:
      - "${CBA_WEBANNO_EXPOSED_PORT}:8080"
    environment:
      - WEBANNO_DB_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - WEBANNO_DB_DRIVER=com.mysql.jdbc.Driver
      - WEBANNO_DB_URL=jdbc:mysql://db:3306/codebookanno?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - WEBANNO_DB_USERNAME=codebookanno
      - WEBANNO_DB_PASSWORD=codebookanno
    volumes:
      - ${PWD}/server-data-2:/export
    depends_on:
      - db
      - cba_api
    restart: unless-stopped
    networks:
      - cba_codeanno
