api:
  api_port: 8081

backend:
  data_root: ${oc.env:CBA_API_DATA_ROOT, ./data}
  use_gpu_for_prediction: 0
  use_gpu_for_training: 0

  redis:
    host_env_var: CBA_API_REDIS_HOST
    port_env_var: CBA_API_REDIS_PORT