api:
  port: 8081

logging:
  rotation: 500
  level: DEBUG

backend:
  data_root: ${oc.env:CBA_API_DATA_ROOT, ./data}
  use_gpu_for_prediction: 0
  use_gpu_for_training: 0

  redis:
    host: ${oc.env:CBA_API_REDIS_HOST, localhost}
    port: ${oc.env:CBA_API_REDIS_PORT, 6379}